# Generated by Django 5.0.1 on 2024-01-03 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_avatar',
            field=models.ImageField(default='default/defaultmale.png', upload_to='uploads/%Y/%m/%d/'),
        ),
    ]
