# Generated by Django 5.0.1 on 2024-01-07 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_alter_profile_gender_alter_profile_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_avatar',
            field=models.ImageField(default='default/defaultmale.png', upload_to='uploads/'),
        ),
    ]
